from numba.cuda.cudadrv.runtime import Runtime
from setuptools import find_packages, setup, Extension
from setuptools.command.install import install
from setuptools.command.build_py import build_py as _build_py
from pathlib import Path
import shutil
import os
import platform
from build_utils import get_b2, build_cpsig, build_cusig, get_paths

#TODO: AVX flag
USE_AVX = False

REBUILD = True
USE_CUDA = 'CUDA_PATH' in os.environ
if 'CUSIG' in os.environ and os.environ['CUSIG'] == 0:
    USE_CUDA = False

# Only support Windows, Linux and MacOS
SYSTEM = platform.system()
if SYSTEM not in ['Windows', 'Linux', 'Darwin']:
    raise RuntimeError("Error while installing pySigLib: unsupported system '" + SYSTEM + "'")

# Don't support CUDA on MacOS
if SYSTEM == 'Darwin':
    USE_CUDA = False

if USE_CUDA:
    print("Found CUDA_PATH, attempting to build with CUDA. To build without CUDA, run 'CUSIG=0 pip install pysiglib' instead.")
else:
    print("Building without CUDA.")

# Get lib extension
if SYSTEM == 'Windows':
    LIB_PREFIX = ''
elif SYSTEM == 'Linux':
    LIB_PREFIX = ''
else:
    LIB_PREFIX = 'lib'

if SYSTEM == 'Windows':
    LIB_EXT = '.dll'
elif SYSTEM == 'Linux':
    LIB_EXT = '.so'
else:
    LIB_EXT = '.dylib'

# Get lib names
LIBS = [LIB_PREFIX + 'cpsig' + LIB_EXT]
if USE_CUDA:
    LIBS += [LIB_PREFIX + 'cusig' + LIB_EXT]

class CustomBuild(_build_py):
    def run(self):
        # Create config file with flags
        parent_dir = Path(__file__).parent
        dir_ = parent_dir / 'pysiglib'
        config_path = dir_ / '_config.py'

        if os.path.exists(config_path):
            os.remove(config_path)

        with open(config_path, 'w') as f:
            f.write(f"# This file is automatically generated by setup.py and should not be edited.\n")
            f.write(f"# It contains information about how the package was built.\n")
            f.write(f"SYSTEM = {repr(SYSTEM)}\n")
            f.write(f"BUILT_WITH_CUDA = {USE_CUDA}\n")
            f.write(f"BUILT_WITH_AVX = {USE_AVX}\n")

        # Proceed with standard build
        super().run()

class CustomInstall(install):
    def run(self):
        if REBUILD:
            get_b2(SYSTEM)
            build_cpsig(SYSTEM)
            if USE_CUDA:
                build_cusig(SYSTEM)
            parent_dir = Path(__file__).parent
            dir_ = parent_dir / 'pysiglib'

            for file in LIBS:
                path = parent_dir / 'siglib' / 'x64' / 'Release' / file
                shutil.copy(path, dir_)

        super().run()

setup(
    name='pysiglib',
    version="0.1.0",
    packages=['pysiglib'],
    include_package_data=True,
    package_data={'': LIBS},
    cmdclass={
        'build_py': CustomBuild,
        'install': CustomInstall,
    },
)
